package com.shooting_simulator.robot;

// THIS FILE IS AUTO-GENERATED BY THE SHOOTER SIMULATOR. DO NOT EDIT MANUALLY.
//
// ==========================================================
// FRC 2026 REBUILT - Kinematics Simulation Profile
// ==========================================================
// Dataset Statistics:
// - Total Simulated Points: 3,710
// - Simulator Resolution:   ORBIT
//
// Environment & Target:
// - Initial Height:         0.51 m
// - Target Height:          1.828 m
// - Target Radius:          0.5 m
//
// Aerodynamics:
// - Projectile Shape:       BALL
// - Mass (kg):              0.22
// - Radius (m):             0.075
// - Drag Coefficient:       0.47
//
// Hardware Limits:
// - Flywheel Velocity:      4 to 12 m/s
// - Pivot Angle:            51° to 79°
// - Velocity Error Margin:  ±0.1 m/s
// - Angle Error Margin:     ±0.2°
//
// Optimizer / Cost Config:
// - Active Preset:          CUSTOM
//   * Robustness Wt:        0.5
//   * Init Vel Wt:          1
//   * Impact Vel Wt:        0
//   * Flight Time Wt:       0
//   * Entry Angle Wt:       0
//   * Target Impact Angle:  -50°
// ==========================================================
public class GeneratedShooterModel extends ShootingModel {

    @Override
    protected double getMinAngle() { return 51; }

    @Override
    protected double getMaxAngle() { return 79; }

    @Override
    protected double getTargetRadius() { return 0.5; }

    // === OPTIMAL ANGLE TARGETS ===

    @Override
    public double getAngle(double d, double vr) {
        return (89.2051053479) -
                (12.4465430509 * d) -
                (9.5209321287 * vr) +
                (2.2635581275 * d * d) +
                (1.0346995968 * d * vr) +
                (0.1354237219 * vr * vr) -
                (0.3142423331 * d * d * d) +
                (0.0114188082 * d * d * vr) +
                (0.1452142113 * d * vr * vr) +
                (0.0663764718 * vr * vr * vr) +
                (0.0288464745 * d * d * d * d) -
                (0.0108197090 * d * d * d * vr) -
                (0.0323661616 * d * d * vr * vr) -
                (0.0220074454 * d * vr * vr * vr) -
                (0.0050967398 * vr * vr * vr * vr) -
                (0.0012239146 * d * d * d * d * d) +
                (0.0006202949 * d * d * d * d * vr) +
                (0.0019916646 * d * d * d * vr * vr) +
                (0.0017248250 * d * d * vr * vr * vr) +
                (0.0006169962 * d * vr * vr * vr * vr) +
                (0.0000529908 * vr * vr * vr * vr * vr);
    }
    @Override
    public double getAngleDerivativeDistance(double d, double vr) {
        return  -
                (12.4465430509) +
                (4.5271162550 * d) +
                (1.0346995968 * vr) -
                (0.9427269994 * d * d) +
                (0.0228376165 * d * vr) +
                (0.1452142113 * vr * vr) +
                (0.1153858982 * d * d * d) -
                (0.0324591271 * d * d * vr) -
                (0.0647323232 * d * vr * vr) -
                (0.0220074454 * vr * vr * vr) -
                (0.0061195731 * d * d * d * d) +
                (0.0024811796 * d * d * d * vr) +
                (0.0059749938 * d * d * vr * vr) +
                (0.0034496500 * d * vr * vr * vr) +
                (0.0006169962 * vr * vr * vr * vr);
    }
    @Override
    public double getAngleDerivativeRadialVelocity(double d, double vr) {
        return  -
                (9.5209321287) +
                (1.0346995968 * d) +
                (0.2708474439 * vr) +
                (0.0114188082 * d * d) +
                (0.2904284226 * d * vr) +
                (0.1991294155 * vr * vr) -
                (0.0108197090 * d * d * d) -
                (0.0647323232 * d * d * vr) -
                (0.0660223362 * d * vr * vr) -
                (0.0203869594 * vr * vr * vr) +
                (0.0006202949 * d * d * d * d) +
                (0.0039833292 * d * d * d * vr) +
                (0.0051744750 * d * d * vr * vr) +
                (0.0024679848 * d * vr * vr * vr) +
                (0.0002649539 * vr * vr * vr * vr);
    }

    // === OPTIMAL VELOCITY TARGETS ===

    @Override
    public double getVelocityNormal(double d, double vr) {
        return (6.1014839877) +
                (0.4017873218 * d) +
                (0.0343296426 * vr) +
                (0.0683317591 * d * d) +
                (0.2031706240 * d * vr) +
                (0.0781127692 * vr * vr) -
                (0.0105445711 * d * d * d) -
                (0.0321154579 * d * d * vr) -
                (0.0116198221 * d * vr * vr) -
                (0.0011863456 * vr * vr * vr) +
                (0.0008204681 * d * d * d * d) +
                (0.0030065638 * d * d * d * vr) +
                (0.0006289263 * d * d * vr * vr) -
                (0.0004317652 * d * vr * vr * vr) -
                (0.0002550551 * vr * vr * vr * vr) -
                (0.0000271352 * d * d * d * d * d) -
                (0.0001288385 * d * d * d * d * vr) -
                (0.0000070241 * d * d * d * vr * vr) +
                (0.0000601363 * d * d * vr * vr * vr) +
                (0.0000470128 * d * vr * vr * vr * vr) +
                (0.0000117582 * vr * vr * vr * vr * vr);
    }
    @Override
    public double getVelocityNormalDerivativeDistance(double d, double vr) {
        return (0.4017873218) +
                (0.1366635182 * d) +
                (0.2031706240 * vr) -
                (0.0316337132 * d * d) -
                (0.0642309157 * d * vr) -
                (0.0116198221 * vr * vr) +
                (0.0032818725 * d * d * d) +
                (0.0090196913 * d * d * vr) +
                (0.0012578526 * d * vr * vr) -
                (0.0004317652 * vr * vr * vr) -
                (0.0001356760 * d * d * d * d) -
                (0.0005153542 * d * d * d * vr) -
                (0.0000210722 * d * d * vr * vr) +
                (0.0001202726 * d * vr * vr * vr) +
                (0.0000470128 * vr * vr * vr * vr);
    }
    @Override
    public double getVelocityNormalDerivativeRadialVelocity(double d, double vr) {
        return (0.0343296426) +
                (0.2031706240 * d) +
                (0.1562255383 * vr) -
                (0.0321154579 * d * d) -
                (0.0232396443 * d * vr) -
                (0.0035590367 * vr * vr) +
                (0.0030065638 * d * d * d) +
                (0.0012578526 * d * d * vr) -
                (0.0012952956 * d * vr * vr) -
                (0.0010202202 * vr * vr * vr) -
                (0.0001288385 * d * d * d * d) -
                (0.0000140481 * d * d * d * vr) +
                (0.0001804088 * d * d * vr * vr) +
                (0.0001880510 * d * vr * vr * vr) +
                (0.0000587912 * vr * vr * vr * vr);
    }

    @Override
    public double getVelocityMinAngle(double d, double vr) {
        return (7.8930007517) -
                (0.2855080441 * d) -
                (1.6602399051 * vr) +
                (0.1128214258 * d * d) +
                (0.7609950621 * d * vr) +
                (0.4645704702 * vr * vr) -
                (0.0013217983 * d * d * d) -
                (0.0832659490 * d * d * vr) -
                (0.0993634705 * d * vr * vr) -
                (0.0282621658 * vr * vr * vr) -
                (0.0003706761 * d * d * d * d) +
                (0.0031023179 * d * d * d * vr) +
                (0.0059559659 * d * d * vr * vr) +
                (0.0036291749 * d * vr * vr * vr) +
                (0.0007412260 * vr * vr * vr * vr);
    }
    @Override
    public double getVelocityMinAngleDerivativeDistance(double d, double vr) {
        return  -
                (0.2855080441) +
                (0.2256428516 * d) +
                (0.7609950621 * vr) -
                (0.0039653948 * d * d) -
                (0.1665318981 * d * vr) -
                (0.0993634705 * vr * vr) -
                (0.0014827045 * d * d * d) +
                (0.0093069537 * d * d * vr) +
                (0.0119119319 * d * vr * vr) +
                (0.0036291749 * vr * vr * vr);
    }
    @Override
    public double getVelocityMinAngleDerivativeRadialVelocity(double d, double vr) {
        return  -
                (1.6602399051) +
                (0.7609950621 * d) +
                (0.9291409403 * vr) -
                (0.0832659490 * d * d) -
                (0.1987269409 * d * vr) -
                (0.0847864975 * vr * vr) +
                (0.0031023179 * d * d * d) +
                (0.0119119319 * d * d * vr) +
                (0.0108875246 * d * vr * vr) +
                (0.0029649042 * vr * vr * vr);
    }

    @Override
    public double getVelocityMaxAngle(double d, double vr) {
        return (5.9609461729) -
                (0.4202906682 * d) -
                (0.6280497480 * vr) +
                (1.2007552887 * d * d) +
                (1.8423261726 * d * vr) +
                (0.5809926136 * vr * vr) -
                (0.1687492632 * d * d * d) -
                (0.0392504104 * d * d * vr) +
                (0.3260508145 * d * vr * vr) +
                (0.1768186751 * vr * vr * vr) +
                (0.0077842312 * d * d * d * d) -
                (0.0012295811 * d * d * d * vr) +
                (0.0005501299 * d * d * vr * vr) +
                (0.0313459565 * d * vr * vr * vr) +
                (0.0196494127 * vr * vr * vr * vr);
    }
    @Override
    public double getVelocityMaxAngleDerivativeDistance(double d, double vr) {
        return  -
                (0.4202906682) +
                (2.4015105774 * d) +
                (1.8423261726 * vr) -
                (0.5062477897 * d * d) -
                (0.0785008208 * d * vr) +
                (0.3260508145 * vr * vr) +
                (0.0311369247 * d * d * d) -
                (0.0036887432 * d * d * vr) +
                (0.0011002598 * d * vr * vr) +
                (0.0313459565 * vr * vr * vr);
    }
    @Override
    public double getVelocityMaxAngleDerivativeRadialVelocity(double d, double vr) {
        return  -
                (0.6280497480) +
                (1.8423261726 * d) +
                (1.1619852271 * vr) -
                (0.0392504104 * d * d) +
                (0.6521016289 * d * vr) +
                (0.5304560254 * vr * vr) -
                (0.0012295811 * d * d * d) +
                (0.0011002598 * d * d * vr) +
                (0.0940378695 * d * vr * vr) +
                (0.0785976506 * vr * vr * vr);
    }

    // === FLIGHT TIME TARGETS ===

    @Override
    public double getFlightTimeNormal(double d, double vr) {
        return (0.6838662058) +
                (0.1824029957 * d) +
                (0.0073430455 * vr) -
                (0.0429840583 * d * d) -
                (0.0026678967 * d * vr) -
                (0.0023553739 * vr * vr) +
                (0.0095169274 * d * d * d) +
                (0.0011808800 * d * d * vr) +
                (0.0000894554 * d * vr * vr) -
                (0.0000528627 * vr * vr * vr) -
                (0.0011098682 * d * d * d * d) -
                (0.0000797922 * d * d * d * vr) +
                (0.0001980515 * d * d * vr * vr) +
                (0.0001854303 * d * vr * vr * vr) +
                (0.0000619763 * vr * vr * vr * vr) +
                (0.0000523199 * d * d * d * d * d) -
                (0.0000001255 * d * d * d * d * vr) -
                (0.0000240819 * d * d * d * vr * vr) -
                (0.0000290856 * d * d * vr * vr * vr) -
                (0.0000184846 * d * vr * vr * vr * vr) -
                (0.0000053330 * vr * vr * vr * vr * vr);
    }

    @Override
    public double getFlightTimeMinAngle(double d, double vr) {
        return  -
                (1.3712770985) +
                (1.1311258487 * d) +
                (0.6613074616 * vr) -
                (0.2252714761 * d * d) -
                (0.2448439079 * d * vr) -
                (0.0733120753 * vr * vr) +
                (0.0234717997 * d * d * d) +
                (0.0365438814 * d * d * vr) +
                (0.0252615681 * d * vr * vr) +
                (0.0064214382 * vr * vr * vr) -
                (0.0009684689 * d * d * d * d) -
                (0.0018236902 * d * d * d * vr) -
                (0.0018700082 * d * d * vr * vr) -
                (0.0010910495 * d * vr * vr * vr) -
                (0.0001829827 * vr * vr * vr * vr);
    }

    @Override
    public double getFlightTimeMaxAngle(double d, double vr) {
        return (0.2399607925) +
                (0.6127067335 * d) +
                (0.3054438343 * vr) -
                (0.0188322170 * d * d) +
                (0.1471299406 * d * vr) +
                (0.1075557322 * vr * vr) +
                (0.0006400414 * d * d * d) -
                (0.0017616385 * d * d * vr) +
                (0.0153938790 * d * vr * vr) +
                (0.0133983927 * vr * vr * vr);
    }

    // === POS VELOCITY TOLERANCE TARGETS ===

    @Override
    public double getToleranceVelPositiveNormal(double d, double vr) {
        return (1.5559929311) -
                (1.2473323784 * d) -
                (0.3251592549 * vr) +
                (0.5608987220 * d * d) +
                (0.2690138922 * d * vr) +
                (0.0432993457 * vr * vr) -
                (0.1346079335 * d * d * d) -
                (0.0905828954 * d * d * vr) -
                (0.0257312622 * d * vr * vr) -
                (0.0018435114 * vr * vr * vr) +
                (0.0163610056 * d * d * d * d) +
                (0.0139352148 * d * d * d * vr) +
                (0.0054177554 * d * d * vr * vr) +
                (0.0005750085 * d * vr * vr * vr) -
                (0.0001147813 * vr * vr * vr * vr) -
                (0.0007903265 * d * d * d * d * d) -
                (0.0008050161 * d * d * d * d * vr) -
                (0.0003863688 * d * d * d * vr * vr) -
                (0.0000430939 * d * d * vr * vr * vr) +
                (0.0000326450 * d * vr * vr * vr * vr) +
                (0.0000102511 * vr * vr * vr * vr * vr);
    }

    @Override
    public double getToleranceVelPositiveMinAngle(double d, double vr) {
        return  -
                (0.1969182495) +
                (0.1083045330 * d) +
                (0.3417993708 * vr) -
                (0.0035640458 * d * d) -
                (0.0761502151 * d * vr) -
                (0.0424025614 * vr * vr) -
                (0.0005639540 * d * d * d) +
                (0.0045197533 * d * d * vr) +
                (0.0049452412 * d * vr * vr) +
                (0.0015320777 * vr * vr * vr);
    }

    @Override
    public double getToleranceVelPositiveMaxAngle(double d, double vr) {
        return  -
                (1.5353804081) +
                (3.7462657294 * d) +
                (1.5713571353 * vr) -
                (1.4926099984 * d * d) +
                (0.6236639937 * d * vr) +
                (1.0103084167 * vr * vr) +
                (0.0775918255 * d * d * d) -
                (0.8962565721 * d * d * vr) -
                (0.5714004214 * d * vr * vr) +
                (0.1304423754 * vr * vr * vr) +
                (0.0083536294 * d * d * d * d) +
                (0.0625547131 * d * d * d * vr) -
                (0.1694276857 * d * d * vr * vr) -
                (0.2194903225 * d * vr * vr * vr) -
                (0.0269030325 * vr * vr * vr * vr) -
                (0.0014201116 * d * d * d * d * d) -
                (0.0058467123 * d * d * d * d * vr) -
                (0.0063832571 * d * d * d * vr * vr) -
                (0.0271433608 * d * d * vr * vr * vr) -
                (0.0316334900 * d * vr * vr * vr * vr) -
                (0.0076425346 * vr * vr * vr * vr * vr);
    }

    // === NEG VELOCITY TOLERANCE TARGETS ===

    @Override
    public double getToleranceVelNegativeNormal(double d, double vr) {
        return (1.3220546487) -
                (0.9504044630 * d) -
                (0.2257420394 * vr) +
                (0.4069814886 * d * d) +
                (0.1743649680 * d * vr) +
                (0.0268623276 * vr * vr) -
                (0.0949524021 * d * d * d) -
                (0.0560050546 * d * d * vr) -
                (0.0146253093 * d * vr * vr) -
                (0.0007146277 * vr * vr * vr) +
                (0.0113427540 * d * d * d * d) +
                (0.0083590949 * d * d * d * vr) +
                (0.0029063669 * d * d * vr * vr) +
                (0.0001321912 * d * vr * vr * vr) -
                (0.0001162243 * vr * vr * vr * vr) -
                (0.0005417946 * d * d * d * d * d) -
                (0.0004734156 * d * d * d * d * vr) -
                (0.0001995825 * d * d * d * vr * vr) -
                (0.0000005223 * d * d * vr * vr * vr) +
                (0.0000301411 * d * vr * vr * vr * vr) +
                (0.0000083055 * vr * vr * vr * vr * vr);
    }

    @Override
    public double getToleranceVelNegativeMinAngle(double d, double vr) {
        return  -
                (0.3537243724) +
                (0.1654928501 * d) +
                (0.4157418829 * vr) -
                (0.0105526373 * d * d) -
                (0.0938106651 * d * vr) -
                (0.0530791914 * vr * vr) -
                (0.0002835044 * d * d * d) +
                (0.0056266919 * d * d * vr) +
                (0.0061439183 * d * vr * vr) +
                (0.0020821939 * vr * vr * vr);
    }

    @Override
    public double getToleranceVelNegativeMaxAngle(double d, double vr) {
        return  -
                (3.1620267404) +
                (4.3548363938 * d) -
                (0.2264709528 * vr) +
                (0.9493679053 * d * d) +
                (6.7510208044 * d * vr) +
                (3.0685916993 * vr * vr) -
                (1.7215031199 * d * d * d) -
                (4.6578672167 * d * d * vr) -
                (1.7400477082 * d * vr * vr) +
                (0.3648738384 * vr * vr * vr) +
                (0.3974414307 * d * d * d * d) +
                (0.8177340482 * d * d * d * vr) +
                (0.0952357899 * d * d * vr * vr) -
                (0.1179601215 * d * vr * vr * vr) +
                (0.0820944104 * vr * vr * vr * vr) -
                (0.0299582974 * d * d * d * d * d) -
                (0.0671871106 * d * d * d * d * vr) -
                (0.0541540239 * d * d * d * vr * vr) -
                (0.0671884802 * d * d * vr * vr * vr) -
                (0.0432393301 * d * vr * vr * vr * vr) -
                (0.0002782098 * vr * vr * vr * vr * vr);
    }

    // === POS ANGLE TOLERANCE TARGETS ===

    @Override
    public double getToleranceAnglePositiveNormal(double d, double vr) {
        return (6.7833939709) -
                (0.9184086826 * d) +
                (0.2911293051 * vr) +
                (0.5506318182 * d * d) +
                (0.2735096965 * d * vr) +
                (0.0393216691 * vr * vr) -
                (0.1036407098 * d * d * d) -
                (0.0072209726 * d * d * vr) +
                (0.0319200353 * d * vr * vr) -
                (0.0087375812 * vr * vr * vr) +
                (0.0112204922 * d * d * d * d) +
                (0.0027699028 * d * d * d * vr) +
                (0.0081013758 * d * d * vr * vr) +
                (0.0138631936 * d * vr * vr * vr) -
                (0.0000027690 * vr * vr * vr * vr) -
                (0.0005177636 * d * d * d * d * d) -
                (0.0003225998 * d * d * d * d * vr) -
                (0.0010257936 * d * d * d * vr * vr) -
                (0.0008601734 * d * d * vr * vr * vr) +
                (0.0008911853 * d * vr * vr * vr * vr) +
                (0.0003066787 * vr * vr * vr * vr * vr);
    }

    @Override
    public double getToleranceAnglePositiveMinAngle(double d, double vr) {
        return (246.6567782132) -
                (66.2351372415 * d) -
                (119.7683576318 * vr) +
                (6.5103537453 * d * d) +
                (21.3591055092 * d * vr) +
                (20.1750354086 * vr * vr) -
                (0.2286152819 * d * d * d) -
                (1.0197425416 * d * d * vr) -
                (1.7684594881 * d * vr * vr) -
                (1.1637752037 * vr * vr * vr);
    }

    @Override
    public double getToleranceAnglePositiveMaxAngle(double d, double vr) {
        return (932.9395338151) -
                (2949.4987966918 * d) -
                (2500.0473893520 * vr) +
                (3062.5434569730 * d * d) +
                (4833.5069807544 * d * vr) +
                (1778.2734724293 * vr * vr) -
                (1270.6747489450 * d * d * d) -
                (2838.1641121916 * d * d * vr) -
                (1989.6357197622 * d * vr * vr) -
                (442.7491932341 * vr * vr * vr) +
                (272.2279179816 * d * d * d * d) +
                (973.8021225589 * d * d * d * vr) +
                (1382.9604001939 * d * d * vr * vr) +
                (938.7590191849 * d * vr * vr * vr) +
                (255.1112972691 * vr * vr * vr * vr);
    }

    // === NEG ANGLE TOLERANCE TARGETS ===

    @Override
    public double getToleranceAngleNegativeNormal(double d, double vr) {
        return (6.7676767362) -
                (0.9275109796 * d) +
                (0.2741417618 * vr) +
                (0.5468881287 * d * d) +
                (0.2713338478 * d * vr) +
                (0.0295315775 * vr * vr) -
                (0.1030231178 * d * d * d) -
                (0.0082583517 * d * d * vr) +
                (0.0366281714 * d * vr * vr) -
                (0.0078774347 * vr * vr * vr) +
                (0.0110873602 * d * d * d * d) +
                (0.0024746337 * d * d * d * vr) +
                (0.0059811393 * d * d * vr * vr) +
                (0.0129943434 * d * vr * vr * vr) +
                (0.0002119396 * vr * vr * vr * vr) -
                (0.0005101754 * d * d * d * d * d) -
                (0.0002985570 * d * d * d * d * vr) -
                (0.0008993831 * d * d * d * vr * vr) -
                (0.0009439710 * d * d * vr * vr * vr) +
                (0.0006519050 * d * vr * vr * vr * vr) +
                (0.0002187725 * vr * vr * vr * vr * vr);
    }

    @Override
    public double getToleranceAngleNegativeMinAngle(double d, double vr) {
        return (232.3797141355) -
                (62.2504509522 * d) -
                (112.3245081902 * vr) +
                (6.1140307189 * d * d) +
                (20.0130681872 * d * vr) +
                (18.8565111005 * vr * vr) -
                (0.2146474960 * d * d * d) -
                (0.9553475503 * d * d * vr) -
                (1.6526641134 * d * vr * vr) -
                (1.0845617996 * vr * vr * vr);
    }

    @Override
    public double getToleranceAngleNegativeMaxAngle(double d, double vr) {
        return (1651.5572153205) -
                (4358.3474792865 * d) -
                (3222.2653211582 * vr) +
                (3728.6687772577 * d * d) +
                (4982.8661433151 * d * vr) +
                (1449.9552506390 * vr * vr) -
                (1173.5282543751 * d * d * d) -
                (2085.2039620043 * d * d * vr) -
                (1089.1196726765 * d * vr * vr) -
                (191.6396716684 * vr * vr * vr) +
                (122.8507269160 * d * d * d * d) +
                (276.8220487721 * d * d * d * vr) +
                (232.5150801674 * d * d * vr * vr) +
                (103.0613359627 * d * vr * vr * vr) +
                (20.0269789080 * vr * vr * vr * vr);
    }

    // === ELLIPSE ANGLE TOLERANCE TARGETS ===

    @Override
    public double getToleranceEllipseAngleNormal(double d, double vr) {
        return (13.2805166515) -
                (8.7025067878 * d) -
                (3.0267154951 * vr) +
                (3.5546639591 * d * d) +
                (1.8723791503 * d * vr) +
                (0.4135299148 * vr * vr) -
                (0.8215911126 * d * d * d) -
                (0.5934992124 * d * d * vr) -
                (0.2338325447 * d * vr * vr) -
                (0.0299576509 * vr * vr * vr) +
                (0.0979241869 * d * d * d * d) +
                (0.0891335805 * d * d * d * vr) +
                (0.0487102977 * d * d * vr * vr) +
                (0.0107687155 * d * vr * vr * vr) +
                (0.0003550127 * vr * vr * vr * vr) -
                (0.0046680805 * d * d * d * d * d) -
                (0.0050596967 * d * d * d * d * vr) -
                (0.0034372704 * d * d * d * vr * vr) -
                (0.0009693189 * d * d * vr * vr * vr) +
                (0.0000109300 * d * vr * vr * vr * vr) +
                (0.0000451113 * vr * vr * vr * vr * vr);
    }

    @Override
    public double getToleranceEllipseAngleMinAngle(double d, double vr) {
        return  -
                (7.8979602437) +
                (0.0716624018 * d) -
                (4.3080018926 * vr) -
                (2.0236902917 * d * d) +
                (12.4006958418 * d * vr) -
                (2.8791762479 * vr * vr) +
                (0.8565543790 * d * d * d) -
                (2.5805520373 * d * d * vr) -
                (3.3757977956 * d * vr * vr) +
                (2.5611381717 * vr * vr * vr) -
                (0.1116091837 * d * d * d * d) +
                (0.1289743255 * d * d * d * vr) +
                (0.6961154266 * d * d * vr * vr) +
                (0.1210198345 * d * vr * vr * vr) -
                (0.4744848034 * vr * vr * vr * vr) +
                (0.0047592182 * d * d * d * d * d) +
                (0.0017565874 * d * d * d * d * vr) -
                (0.0313277838 * d * d * d * vr * vr) -
                (0.0354964497 * d * d * vr * vr * vr) +
                (0.0152038244 * d * vr * vr * vr * vr) +
                (0.0272140761 * vr * vr * vr * vr * vr);
    }

    @Override
    public double getToleranceEllipseAngleMaxAngle(double d, double vr) {
        return  -
                (7.8088049605) +
                (32.0919212848 * d) +
                (27.4883785299 * vr) -
                (29.2606770778 * d * d) -
                (37.6670642325 * d * vr) -
                (6.7517379445 * vr * vr) +
                (15.1033307770 * d * d * d) +
                (25.6338484809 * d * d * vr) +
                (9.8764378242 * d * vr * vr) +
                (1.0017060405 * vr * vr * vr) -
                (2.7545266980 * d * d * d * d) -
                (4.2325979080 * d * d * d * vr) -
                (0.5180190988 * d * d * vr * vr) +
                (0.4907073081 * d * vr * vr * vr) -
                (0.0688685398 * vr * vr * vr * vr) +
                (0.1958738937 * d * d * d * d * d) +
                (0.4207303771 * d * d * d * d * vr) +
                (0.5015703328 * d * d * d * vr * vr) +
                (0.6258375682 * d * d * vr * vr * vr) +
                (0.3754035793 * d * vr * vr * vr * vr) +
                (0.0580670047 * vr * vr * vr * vr * vr);
    }
}